language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "4.2"

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - sudo update-java-alternatives -s java-8-oracle
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - java -version
  - wget https://www.dropbox.com/s/706gkkfkn7gpar7/apache-cassandra-3.0.6.tar.gz?dl=1 -O apache-cassandra-3.0.6.tar.gz && tar -xvzf apache-cassandra-3.0.6.tar.gz
  - sudo sh ./apache-cassandra-3.0.6/bin/cassandra -R
  - sleep 20

