language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "4.2"

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default

before_install:
  - java -version
  - sudo rm -rf /var/lib/cassandra/*
  - wget http://www.us.apache.org/dist/cassandra/3.3/apache-cassandra-3.3-bin.tar.gz && tar -xvzf apache-cassandra-3.3-bin.tar.gz && sudo sh apache-cassandra-3.3/bin/cassandra
